disabled_rules:
  - colon
  - comma
  - control_statement
  - unused_closure_parameter

opt_in_rules:
  - empty_count
  - vertical_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

vertical_whitespace:
  max_empty_lines: 1

mark:
  severity: warning

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

analyzer_rules:
  - explicit_self

excluded:
  - Carthage
  - Pods
  - DerivedData

allow_zero_lintable_files: false
check_for_updates: true

force_cast: warning
force_try:
  severity: warning

line_length: 150

type_body_length:
  - 300
  - 400

included:
  - SpaceX-PetProject
  - SpaceX-PetProjectTests
  - SpaceX-PetProjectUITests

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]

identifier_name:
  min_length:
    warning: 1
    error: 1

reporter: "xcode"
