disabled_rules:
  - colon
  - comma
  - control_statement

opt_in_rules:
  - empty_count

analyzer_rules:
  - explicit_self

line_length: 110

type_body_length: [300, 400]
file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length: { warning: 40, error: 50 }
  allowed_symbols: ["_"]

identifier_name:
  min_length:
    error: 4
